blank_issues_enabled: false
contact_links:
  - name: GitHub Wiki
    url: https://github.com/Bloodchild8906/dnd5echar/wiki
    about: Check the wiki for documentation and guides

  - name: Troubleshooting
    url: https://github.com/Bloodchild8906/dnd5echar/wiki/Troubleshooting
    about: Find solutions to common issues

  - name: Contributing Guidelines
    url: https://github.com/Bloodchild8906/dnd5echar/wiki/Contributing
    about: Learn how to contribute to this project
