name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
        env:
          VITE_APP_ENV: production
          VITE_APP_NAME: 5e Sheet Manager
          VITE_DEFAULT_OPEN5E_DOCUMENT: 5esrd
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
